### ISSUE TITLE
Relazione: Descrizione Generale

### ISSUE THREAD

**Issue by pietrogb** [sebastianomarchesini/SaloneAnna#11]
Descrizione iniziale;
- [x] Il sito

- [x] Vincoli generali

- [x] Analisi dei requisiti;

**Comment by sebastianomarchesini** [comment]
@pit1988 Vincoli generali tipo?

**Comment by pietrogb** [comment]
@sebastianomarchesini  Quelli scritti nella relazione di GGarden (Il sito dev'essere accessibile da parte di categorie d'utenti diversificate ed utilizzando dispositivi diversi compresi smartphones e tablet; valido secondo w3c, separazione struttura-presentazione-comportamento)
