### ISSUE TITLE
Sessioni

### ISSUE THREAD

**Issue by pietrogb** [sebastianomarchesini/SaloneAnna#2]
Inserire il timer sulle sessioni al momento della creazione. Vedere slide della Gaggi

**Comment by pietrogb** [comment]
Implementata da Andrea

**Comment by Cenze94** [comment]
Sì ancora da testare comunque, e tra l'altro è da correggere perché è da fargli richiamare il logout o comunque da fargli cancellare la sessione quando il tempo è scaduto, prima però devo accertarmi che logout sia corretto, in modo da non dover fare correzioni doppie
