### ISSUE TITLE
Relazione: Accessibilità

### ISSUE THREAD

**Issue by pietrogb** [sebastianomarchesini/SaloneAnna#21]

**Comment by sebastianomarchesini** [comment]
**Listino Prezzi e Tabelle Varie**
Nelle specifiche HTML 4.01 e nelle WCAG 1.0 si raccomanda agli sviluppatori di non usare le tabelle a scopo di presentazione (“layout tables”), ma di riservarne l’uso alla funzione strutturale per la quale sono state progettate: incasellare dati tabellari.  Così è stato per il nostro sito Salone Anna. Ecco i punti introdotti per rendere accessibile la tabella:

- Aggiunto attributo _summary_ nell’elemento table. Il suo scopo è fornire una descrizione della struttura e del contenuto della tabella.

- Elemento _th_ che ne definisce l'intestazione. La tabella d’esempio resa accessibile viene dunque divisa in celle d’intestazione, che ci dicono che tipo d’informazioni contengono le varie colonne, e celle di dati (marcate da elementi td)

- Relazione tra celle d’intestazione e celle di dati è resa esplicita per mezzo dell’attributo _scope_. Quest’attributo indica quindi qual è l’estensione di celle per cui valgono come informazioni d’intestazione quelle contenute nella cella marcata con l’attributo _scope_. Nel nostro caso marcato _scope_ con valore _col_ le celle d'intestazione. Si assicura che le informazioni di intestazione si applicano alle rimanenti celle della colonna.

- Serie di _id_ e di _headers_. Tramite l’attributo _id_ si identifica una cella che contiene informazioni di intestazione: dunque tutte le celle marcate con TH, ma anche le celle marcate con td nella prima colonna, le quali contengono il nome del corso a cui fanno riferimento le successive celle di dati sulla medesima riga. L’attributo _headers_ serve per risalire alle celle d’intestazione da porre in relazione con la cella corrente. Questo per dare maggior facilità e orientamento agli screen reader che si ricordano le intestazioni.

- Agginto elemento _caption_ subito dopo l'elemento _table_ con funzione simile a _summary_.

- THEAD, TBODY – Questi due elementi servono per differenziare una tabella in due parti: testata e corpo.

- Colspan usato per unire nel nostro caso per unire due colonne e una piccola intestazione di un gruppo di prodotti.
